name = str(input("이름을 입력하세요: "))
num = str(input("학번을 입력하세요: "))
dep = str(input("학과를 입력하세요: "))
univ = str(input("학교를 입력하세요: "))

print("\n<출력>")
print("이름:", name)
print("학번:", num)
print("학과:", dep)
print("학교:", univ)
